article_id: 1
title: "JavaScript data types and data structures"
description: "Programming languages all have built-in data structures, but these often differ from one language to another. This article attempts to list the built-"
views: 3
category: "LLM"
is_kid: false
is_series: true
series_sequence: 1
author:
  author_id: 1
  name: ashique
  email: admin@gmail.com
  photo: photo url
  bio: ML/LLM/DEEPLEARNING Engineer
  github: ashiquemukkiil
  website: www.1littlecoder.com
  created_at: '2023-07-20 10:30:45.123456'
  update_at: '2023-07-20 10:30:45.123456'
series:
  series_id: 1
  title: "Testing series"
  description: "This is all about java script A_Z"
  article:
    - article_id: 1
      title: "JavaScript data types and data structures"
      description: "Programming languages all have built-in data structures, but these often differ from one language to another. This article attempts to list the built-"
      views: 3
      category: "LLM"
      is_kid: false
      is_series: true
      series_sequence: 1
    - article_id: 2
      title: "JavaScript data types and data structures 2"
      description: "Programming languages all have built-in data structures, but these often differ from one language to another. This article attempts to list the built-"
      views: 3
      category: "LLM"
      is_kid: false
      is_series: true
      series_sequence: 2
    - article_id: 3
      title: "JavaScript data types and data structures 3"
      description: "Programming languages all have built-in data structures, but these often differ from one language to another. This article attempts to list the built-"
      views: 3
      category: "LLM"
      is_kid: false
      is_series: true
      series_sequence: 3
seo_title: "javascript-data-types-and-data-structures"
